[project]
name = "opensy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eurocodepy>=2025.12.1",
    "nbformat>=5.10.4",
    "opensees>=0.1.21",
    "openseespy>=3.7.1.2",
    "opstool>=1.0.26",
    "opsvis>=1.3.4",
]

[tool.pyright]
extraPaths = ["standards"]
