import openseespy.opensees as ops
ops.wipe()
ops.model('BasicBuilder', '-ndm', 2, '-ndf', 3)
ops.node(1, 0.0, 0.0)
ops.node(2, 0.0, 0.0)
ops.uniaxialMaterial('Elastic', 1, 1000.0)
ops.element('zeroLength', 1, 1, 2, '-mat', 1, '-dir', 2, '-orient', 0, -1, 0, 1, 0, 0)
ops.fix(2, 1, 1, 1)
ops.timeSeries('Linear', 1)
ops.pattern('Plain', 1, 1)
ops.load(1, 1.0, 0.0, 0.0)
ops.system('BandGeneral')
ops.numberer('RCM')
ops.constraints('Plain')
ops.integrator('LoadControl', 1.0)
ops.algorithm('Linear')
ops.analysis('Static')
ops.analyze(1)
print(f"X disp: {ops.nodeDisp(1, 1)}")
print(f"Y disp: {ops.nodeDisp(1, 2)}")

ops.loadConst('-time', 0.0)
ops.pattern('Plain', 2, 1)
ops.load(1, 0.0, 1.0, 0.0)
ops.analyze(1)
print(f"X disp (load Y): {ops.nodeDisp(1, 1)}")
print(f"Y disp (load Y): {ops.nodeDisp(1, 2)}")
