# This file reads parameter combinations and for each parameter combination it 
# calls the function 'MSSS-Concrete_Box_3-D'. This function creates a finite element
# model corresponding to each of the parameter combinations. Then this code
# performs dynamic analysis for each of the bridges for an earthquake specified 
# in the parameter combination    

# For additional details refer to the readme file for Iputs     

logFile run.log; # creating a log file to record screen output in a file - mainly used for debugging in case of any issues
source MSSS-Concrete_Box_3-D.tcl ; # this is the function which creates a file for ecah set of parameter combinations

set f [open "parameter_value_AB.out" "r"] ; # opening file named 'parameter_value_AB.out' -- this file contains the parameter combinations   

# reading the first 8 lines which contain headers
for {set i 0} {$i < 8} {incr i 1} {
	gets $f line
}

# this loop reads one line at a time from the parameter_value_AB.out file. 
# Each line contains a set of 43 parameteres that define various material and 
# geometric properties of a bridge. The parameter combinations from each row are
# saved in the matrix 'mod'       
for {set i 1} {$i < 1153} {incr i 1} { ;# the 'parameter_value_AB.out' contains 1152 ombinations so the loop groes from 1 to 1152.
	gets $f line
	scan $line "%f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %f %i %f %i %f %f %f %f %f %i %f %f %f %f %f %f %f %f %f %f %i %f %f %f %f %f %f %f" mod($i,0) mod($i,1) mod($i,2) mod($i,3) mod($i,4) mod($i,5) mod($i,6) mod($i,7) mod($i,8) mod($i,9) mod($i,10) mod($i,11) mod($i,12) mod($i,13) mod($i,14) mod($i,15) mod($i,16) mod($i,17) mod($i,18)  mod($i,19) mod($i,20) mod($i,21) mod($i,22) mod($i,23) mod($i,24) mod($i,25) mod($i,26) mod($i,27) mod($i,28) mod($i,29) mod($i,30) mod($i,31) mod($i,32) mod($i,33) mod($i,34) mod($i,35) mod($i,36) mod($i,37)  mod($i,38) mod($i,39) mod($i,40) mod($i,41) mod($i,42)
#                1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
}

# printing out a message that all the parameter combinations have been read
puts "read data"

# setting up parallelization for use with OpenSeesMP
set pid [getPID]
set np [getNP]

set count 0;

# The following loop calls the 'MSSS-Concrete_Box_3-D' function for each parameter
# combination and executes the files generated by the function

for {set i 1} {$i < 1153} {incr i 1} {



  if {[expr $count % $np] == $pid} { ;# this line is for parallelization in OpenSeesMP
  
    puts "This simulation is running on process # $pid" ;# printing out the ID of the processor on which the simulation is performed 

    file delete -force [concat MSSS-Concrete_Box_$i];# Deleting any exisitng output folders from previous runs - important if re-running simulation with different analysis parameters 
    # the line below calls the function 'MSSS-Concrete_Box_3-D' which creates the finite element model and saves in folder  MSSS-Concrete_Box_$i ('i' is the ith parameter combbination)
	MSSS-Concrete_Box_3-D $mod($i,0) $mod($i,1) $mod($i,2) $mod($i,3) $mod($i,4) $mod($i,5) $mod($i,6) $mod($i,7) $mod($i,8) $mod($i,9) $mod($i,10) $mod($i,11) $mod($i,12) $mod($i,13) $mod($i,14) $mod($i,15) $mod($i,16) $mod($i,17) $mod($i,18) $mod($i,19) $mod($i,20) $mod($i,21) $mod($i,22) $mod($i,23) $mod($i,24) $mod($i,25) $mod($i,26) $mod($i,27) $mod($i,28) $mod($i,29) $mod($i,30) $mod($i,31) $mod($i,32) $mod($i,33) $mod($i,34) $mod($i,35) $mod($i,36) $mod($i,37) $mod($i,38) $mod($i,39) $mod($i,40) $mod($i,41) $mod($i,42) $i
    
  
	puts "This is simulation number $i of 1152" ; # printing out simulation number
    source [concat MSSS-Concrete_Box_$i/MSSS-Concrete_Box_$i.tcl] ; # this line runs the finite element model created by the function 'MSSS-Concrete_Box_3-D'.

	wipe ;# wiping workspace for next simulation
    
    # the following 3 lines create a .done file which is used to keep track of simulations that have been completed
    # presence of .done file does not imply convergence or lack thereof. It only implies that the simulation was completed irrespective convergence.
    set fp [open MSSS-Concrete_Box_$i.done w]
    puts $fp "done !!"
    close $fp 
  }
  incr count 1; ;  # this line is for paralleization in OpenSeesMP
}

close $f; # closing the file that contains the parameter combinations 